# -*- coding: utf-8 -*-
"""repaso_eliminación.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UZAs-ULfRvcXLoMJYWgItCkimPcRS-vD
"""

# Instalar PyMuPDF para leer el PDF
!pip install PyMuPDF

# Importar bibliotecas
import fitz  # PyMuPDF
import re    # Expresiones regulares para limpieza de texto

# Ruta del archivo PDF
ruta_pdf = "/content/certificado (1).pdf"

# Abrir el archivo PDF
documento = fitz.open(ruta_pdf)

# Extraer texto de todas las páginas
texto = ""
for pagina in documento:
    texto += pagina.get_text()

print("Texto extraído del PDF:")
print(texto[:500])  # Mostrar solo los primeros 500 caracteres para no saturar la salida

# Función para limpiar el texto
def limpiar_texto(texto, eliminar_numeros=True):
    # Definir los signos de puntuación que queremos eliminar
    signos_puntuacion = ";:"

    # Eliminar los signos de puntuación específicos
    texto_limpio = re.sub(f"[{re.escape(signos_puntuacion)}]", "", texto)

    # Opción para eliminar números
    if eliminar_numeros:
        texto_limpio = re.sub(r"\d+", "", texto_limpio)

    return texto_limpio

# Limpiar el texto
eliminar_numeros = True  # Cambiar a False si no quieres eliminar los números
texto_limpio = limpiar_texto(texto, eliminar_numeros)

print("\nTexto limpio:")
print(texto_limpio[:500])  # Mostrar solo los primeros 500 caracteres

# Verificar el texto limpio
print("\nTexto limpio final:")
print(texto_limpio)

